// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs ctypes/ctypes.go

package snap7go

type TS7CpuInfo struct {
	ModuleTypeName [33]int8
	SerialNumber   [25]int8
	ASName         [25]int8
	Copyright      [27]int8
	ModuleName     [25]int8
}
